// GENERATED by krpc-clientgen — do not edit by hand.
// Regen command (requires KSP running with Career addon deployed):
//   krpc-clientgen csharp KSPMissionControl --output src/KSPMissionControl.MCP/Krpc/KSPMissionControlStubs.cs
//
// This is a hand-written placeholder with the expected shape.
// Replace entirely when you run krpc-clientgen for the first time.

using System.Collections.Generic;
using Google.Protobuf;

namespace KRPC.Client.Services.KSPMissionControl
{
    public static class ExtensionMethods
    {
        public static Service KSPMissionControl(this IConnection connection) => new Service(connection);
    }

    public class Service
    {
        private readonly IConnection _connection;

        internal Service(IConnection connection) => _connection = connection;

        public string GetTechTree()
        {
            var result = _connection.Invoke(
                "KSPMissionControl",
                "GetTechTree",
                new List<ByteString>());
            return (string)Encoder.Decode(result, typeof(string), _connection);
        }
    }
}
